name: marvel_heroes
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Project Structure
  flutter_modular: ^6.3.2

  # Services
  http: ^1.1.0

  #State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2

  # UI, UX and Widgets
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  auto_size_text: ^3.0.0
  dynamic_height_grid_view: ^0.0.3

  # Utils
  freezed: ^2.4.0
  freezed_annotation: ^2.4.1
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

  # Tests
  mocktail:
  faker: ^2.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/marvel.svg